apiVersion: apps/v1                                                             
kind: Deployment                                                                
metadata:                                                                       
  name: kubevirt-cloud-controller-manager
  namespace: kube-system
spec:                                                                           
  template:                                                                     
    spec:                                                                       
      containers:                                                               
      - image: registry:5000/kubevirt-cloud-controller-manager:main
        name: kubevirt-cloud-controller-manager
