apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: kccm-extension-apiserver-authorization-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: cloud-controller-manager
  namespace: default
