generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: kubeconfig
  namespace: default
  files:
  - kubeconfig
- name: infra-kubeconfig
  namespace: default
  files:
  - infra-kubeconfig
