
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --authentication-skip-lookup=true
  target:
    kind: Deployment
- patch: |-
    - op: remove
      path: /rules/4
  target:
    kind: Role
    name: kccm
    namespace: default
- patch: |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: kccm
    $patch: delete
- patch: |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: kccm
    $patch: delete
- patch: |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: kccm
      namespace: kube-system
    $patch: delete


generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - cloud-config
  name: cloud-config
  namespace: default
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
