namespace: kvcluster


patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --cluster-name=$TENANT_CLUSTER_NAME
  target:
    kind: Deployment
- path: manager_image_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../secret
- ../../isolated
